name: simple

services:
  app:
    image: elseh29/simple-amar
    build: ./app
    ports:
      - "5000:3000"
    volumes:
      - vol-simple:/app/public/images/

volumes:
  vol-simple:logging:
  driver: json-file
  options:
    labels: "logging"
    env: "logging"
    compress: "true"
    max-size: "10m"
    max-file: "3"